<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <RootNamespace>MVMediaDownloaderUpdater</RootNamespace>
    <AssemblyName>MV Media Downloader Updater</AssemblyName>
    <StartupObject>MVMediaDownloaderUpdater.Updater</StartupObject>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Updater.cs" Link="Updater.cs" />
  </ItemGroup>
</Project>
